// Code generated by hertz generator.

package k8s

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdeploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdeploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _namespaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdeploymentbynameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdeploymentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdeploymentlist0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdeployment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeployment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rollbackMw() []app.HandlerFunc {
	// your code...
	return nil
}
