// Code generated by hertz generator.

package ops

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buildlogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletejobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deployappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _restartappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rollbackappMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateappMw() []app.HandlerFunc {
	// your code...
	return nil
}
