// Code generated by hertz generator.

package image

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getimageinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imagebuildMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imagepullMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imagepushMw() []app.HandlerFunc {
	// your code...
	return nil
}
