// Code generated by hertz generator.

package analyse

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproject0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _compareinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _compareinfo0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbranchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbranch0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _branchnameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtag0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectid0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectid1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectnameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectname0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectname1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _branchname0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mergereqMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectname2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mergereq0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _branchname1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clonecodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
