// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	analyse "pangoo/katalyst/biz/router/analyse"
	image "pangoo/katalyst/biz/router/image"
	k8s "pangoo/katalyst/biz/router/k8s"
	ops "pangoo/katalyst/biz/router/ops"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	ops.Register(r)

	//jenkins.Register(r)

	image.Register(r)

	k8s.Register(r)

	analyse.Register(r)
}
